### ISSUE TITLE
Port solution for reason relay to reformality

### ISSUE THREAD

**Issue by isitrita** [shakacode/re-formality#103]
I found that similar issue with `GLIBC_2.29' not found ` which I am experiencing on Vercel for reformality ppx was fixed in https://github.com/zth/rescript-relay/pull/153/files following this discussion https://github.com/zth/rescript-relay/issues/152 and it might be fixed easily for Vercel environment

Could you port this fix to reformality ppx? 

> I think this happens because the executables that are included in reason-relay are dynamically linked to newer versions of GLIBC than are available on the machines that Vercel/Netlify use. One possible solution is to statically link the executables so that they don't have a dependency on GLIBC. I'm planning on working on a PR for this today.

```

20:52:29.000 | FAILED: server/Server__User.ast
-- | --
20:52:29.000 | /vercel/path0/node_modules/re-formality/ppx: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /vercel/path0/node_modules/re-formality/ppx)


```

**Comment by alexfedoseev** [comment]
Hi @isitrita,

It should be fixed in #104. Please, try the `4.0.0-beta.15`.
