### ISSUE TITLE
Problem building on Alpine

### ISSUE THREAD

**Issue by ashutheone** [shakacode/re-formality#92]
While trying to build with **4.0.0-beta.8 version** on node:alpine in Docker container image, we ran into following errors:

`sh: /node_modules/re-formality/ppx: not  #found`
`  We've found a bug for you!`
`  /app/presentation/views/CommonViews.re`
`  Error while running external preprocessor`

We then tried with **4.0.0-beta.9 version** and this error persisted.

**Comment by ashutheone** [comment]
See [Original post](https://github.com/MinimaHQ/re-formality/issues/90#issuecomment-721153959) for a workaround.

**Comment by alexfedoseev** [comment]
Should be fixed in #104. Please, reopen if it's still broken.
