### ISSUE TITLE
Implement a useFormContext hook

### ISSUE THREAD

**Issue by dan003400** [shakacode/re-formality#93]
The ability to create a Form context that can be accessed from anywhere similar to how Formik does it would be super useful.

https://formik.org/docs/api/useFormikContext

**Comment by alexfedoseev** [comment]
As per discussion on Discord, I think that props drilling is safer and enough ergonomic in Reason/ReScript, and I'd encourage preferring it over context in 99% of the cases in general. So I wouldn't increase the API and complexity of the library with this addition.

**Comment by dan003400** [comment]
Totally fair, I agree with that explanation.
